/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  control_quota: () => import("@/views/control/quota/index.vue"),
  control_ratelimit: () => import("@/views/control/ratelimit/index.vue"),
  control_user: () => import("@/views/control/user/index.vue"),
  data_log: () => import("@/views/data/log/index.vue"),
  data_stats: () => import("@/views/data/stats/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "routing_app-profile": () => import("@/views/routing/app-profile/index.vue"),
  "routing_traffic-plan": () => import("@/views/routing/traffic-plan/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  upstream_channel: () => import("@/views/upstream/channel/index.vue"),
  upstream_model: () => import("@/views/upstream/model/index.vue"),
  user_key: () => import("@/views/user/key/index.vue"),
};
