/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "manage_app-profile": () => import("@/views/manage/app-profile/index.vue"),
  manage_channel: () => import("@/views/manage/channel/index.vue"),
  manage_log: () => import("@/views/manage/log/index.vue"),
  manage_model: () => import("@/views/manage/model/index.vue"),
  manage_quota: () => import("@/views/manage/quota/index.vue"),
  manage_ratelimit: () => import("@/views/manage/ratelimit/index.vue"),
  manage_settings: () => import("@/views/manage/settings/index.vue"),
  manage_stats: () => import("@/views/manage/stats/index.vue"),
  "manage_traffic-plan": () => import("@/views/manage/traffic-plan/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
};
