/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'control',
    path: '/control',
    component: 'layout.base',
    meta: {
      title: '流量控制',
      i18nKey: 'route.control',
      order: 4
    },
    children: [
      {
        name: 'control_quota',
        path: '/control/quota',
        component: 'view.control_quota',
        meta: {
          title: '配额管理',
          i18nKey: 'route.control_quota'
        }
      },
      {
        name: 'control_ratelimit',
        path: '/control/ratelimit',
        component: 'view.control_ratelimit',
        meta: {
          title: '限流管理',
          i18nKey: 'route.control_ratelimit'
        }
      },
      {
        name: 'control_user',
        path: '/control/user',
        component: 'view.control_user',
        meta: {
          title: '用户管理',
          i18nKey: 'route.control_user'
        }
      }
    ]
  },
  {
    name: 'data',
    path: '/data',
    component: 'layout.base',
    meta: {
      title: '数据统计',
      i18nKey: 'route.data',
      order: 5
    },
    children: [
      {
        name: 'data_log',
        path: '/data/log',
        component: 'view.data_log',
        meta: {
          title: '请求日志',
          i18nKey: 'route.data_log'
        }
      },
      {
        name: 'data_stats',
        path: '/data/stats',
        component: 'view.data_stats',
        meta: {
          title: '使用统计',
          i18nKey: 'route.data_stats'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '仪表盘',
      i18nKey: 'route.home',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      hideInMenu: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'routing',
    path: '/routing',
    component: 'layout.base',
    meta: {
      title: '请求分流',
      i18nKey: 'route.routing',
      order: 2
    },
    children: [
      {
        name: 'routing_app-profile',
        path: '/routing/app-profile',
        component: 'view.routing_app-profile',
        meta: {
          title: '应用预设',
          i18nKey: 'route.routing_app-profile'
        }
      },
      {
        name: 'routing_traffic-plan',
        path: '/routing/traffic-plan',
        component: 'view.routing_traffic-plan',
        meta: {
          title: '应用方案',
          i18nKey: 'route.routing_traffic-plan'
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: '系统设置',
      i18nKey: 'route.settings',
      order: 6
    }
  },
  {
    name: 'upstream',
    path: '/upstream',
    component: 'layout.base',
    meta: {
      title: '上游模型',
      i18nKey: 'route.upstream',
      order: 3
    },
    children: [
      {
        name: 'upstream_channel',
        path: '/upstream/channel',
        component: 'view.upstream_channel',
        meta: {
          title: '渠道管理',
          i18nKey: 'route.upstream_channel'
        }
      },
      {
        name: 'upstream_model',
        path: '/upstream/model',
        component: 'view.upstream_model',
        meta: {
          title: '模型管理',
          i18nKey: 'route.upstream_model'
        }
      }
    ]
  }
];
